/*FORMAS NORMAIS:*/



/*PRIMEIRA FORMA NORMAL: [ATOMICIDADE]
	- UMA MODELAGEM MAL FEITA PODE GERAR DIVERSOS PROBLEMAS;
	- LEMBRAR DO BOM DO SOFTWARE;
	- 3 REGRAS:
		- 1 -> TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA.
		- 2 -> TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA. [CAMPO DIVISÍVEL] (ENDERECO PODE SER DIVIDIDO EM = RUA, BAIRRO, CIDADE, ESTADO, ETC.)
		- 3 -> TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO. [PRIMARY KEY]

	- PETER CHEN -> NÃO DEVEMOS MODELAR PENSANDO EM PROCEDIMENTO.

		- CHAVE NATURAL -> PERTENCE A PESSOA, TIPO O CPF, ELA PERTENCE AO REGISTRO.
		- CHAVE ARTIFICIAL -> CRIADA. MUITO MAIS UTILIZADAS PORQUE O BANCO FICA MAIS COESO E E OS DADOS MAIS PROTEGIDOS E ORGANIZADOS.
*/



-------------------------------------------------------------------------------------------------------------------------------------------------------

/*SEGUNDA FORMA NORMAL:
	- SERVE PARA RESOLVER PROBLEMAS EM RELACIONAMENTOS TERNÁRIOS [EVITA DUPLICIDADE].
	- OS CAMPOS CHAVES SÃO TRANSFORMADOS EM CAMPOS COMUNS E, DEPOIS, CRIA-SE UMA CHAVE PRIMÁRIA.
	- A UNIÃO DOS CAMPOS ASSOCIATIVOS FORMAM UM CONJUNTO.
	- DEPENDÊNCIA DIRETA.
	- NA SEGUNDA FORMA NORMAL, QUALQUER CAMPO NÃO CHAVE (NC), PRECISA DEPENDER DA TOTALIDADE DAS CHAVES.
		- ID_PACIENTE + ID_MEDICO + ID_HOSPITAL == CONSULTA.
		- A DATA DEPENDE DA CONSULTA.
		- SENDO ASSIM, A DATA PODE FICAR NA TABELA DA CONSULTA.
		- O CAMPO DIAGNÓSTICO == NÃO CHAVE. E DEPENDE DA TOTALIDADE DA CHAVE PRIMÁRIA.
	
*/








-------------------------------------------------------------------------------------------------------------------------------------------------------

/*TERCEIRA FORMA NORMAL:
	- CAMPO DE DEPENDÊNCIA TRANSITIVA:
		-  INTERNAÇÃO NÃO DEPENDE DA TOTALIDADE DAS CHAVES (ID_PACIENTE + ID_MEDICO + ID_HOSPITAL).
		- A INERNAÇÃO DEPENDE DO DIAGNÓSTICO.
		- OU SEJA, CAMPOS NÃO CHAVE QUE DEPENDEM DE OUTROS CAMPOS NÃO CHAVE == OUTRA TABELA.
*/



-------------------------------------------------------------------------------------------------------------------------------------------------------

/*ESQUEMA DE ORGANIZAÇÃO DE AGENDAMENTO DE CONSULTAS:*/


+------------+				+------------+				+------------+
| PACIENTE   | 				|  MEDICO	 |				| HOSPITAL	 |
+------------+				+------------+				+------------+
| IDPACIENTE | 				| IDMEDICO	 |				| IDHOSPITAL |
| NOME   	 | 				| NOME		 |				| NOME		 |
| SEXO    	 | 				| SEXO		 |				| BAIRRO	 |
| EMAIL  	 | 				| ESPECIALID.|				| CIDADE	 |
| NASCIMENTO |				| FUNCION.	 |				| ESTADO	 |
+------------+				+------------+				+------------+

							+------------+
							| CONSULTA	 |
							+------------+
							| IDCONSULTA |
							|			 |
							| ID_PACIENTE|
							| ID_MEDICO	 |
							| ID_HOSPITAL|
							|			 |
							| DATA		 | ------> 2FN
							| DIAGNOSTICO| ------> 2FN
							+------------+



							+------------+
							| INTERNACAO | ------> 3FN
							+------------+
							| IDINTERNAC.|
							| QUARTO	 |
							| ENTRADA	 |
							| SAIDA	 	 |
							| OBSERVAC.	 |
							| ID_CONSULTA|
							+------------+


/*AS FORMAS NORMAIS SÃO DIRETRIZES, MAS A MODELAGEM É ABSTRATA*/

-------------------------------------------------------------------------------------------------------------------------------------------------------


/*CRIANDO O DATABASE E AS TABLES*/


CREATE DATABASE CONSULTORIO;

USE CONSULTORIO;

CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	NASCIMENTO DATE NOT NULL
);


CREATE TABLE MEDICO(
	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	ESPECIALIDADE VARCHAR (30),
	FUNCIONARIO ENUM ('S', 'N')
);


CREATE TABLE HOSPITAL(
	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2)
);


CREATE TABLE CONSULTA(
	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(100)
);


CREATE TABLE INTERNACAO(
	IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
	ENTRADA DATETIME NOT NULL,
	QUARTO INT NOT NULL,
	SAIDA DATETIME NOT NULL,
	OBSERVACOES VARCHAR(50),
	ID_CONSULTA INT UNIQUE
);


/*CRIANDO AS CONSTRAINTS*/

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONSULTA
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);









