
SELECT * FROM CLIENTE;


/* EXEMPLO ERRADO*/
INSERT INTO CLIENTE VALUES(NULL,'JOAO PAULO', 'M', '07555844599'); /*FALTA UM CAMPO -> EMAIL*/

/* EXEMPLO*/
INSERT INTO CLIENTE VALUES(NULL,'JOAO PAULO', 'M', 'JOAOPAULO@GMAIL.COM', '07555844599');
INSERT INTO CLIENTE VALUES(NULL,'PATRICIA SILVA', 'F', NULL, '07555844589');
INSERT INTO CLIENTE VALUES(NULL,'EDSON ALMEIDA', 'M', 'EDSONALMEIDA@IG.COM', '07555875599');
INSERT INTO CLIENTE VALUES(NULL,'ANA CLARA', 'F', NULL, '07555844369');
INSERT INTO CLIENTE VALUES(NULL,'ALINE MAFRA', 'F', 'MAFRA@GMAIL.COM', '07445844599');


SELECT * FROM CLIENTE;


/* INSERÇÕES EM RELACIONAMETO 1X1: */

INSERT INTO ENDERECO VALUES(NULL, 'RUA PEDRO VIDAL DA CRUZ', 'BOQUEIRAO', 'GUARAPUAVA', 'PR', 8);
INSERT INTO ENDERECO VALUES(NULL, 'INACIO KARPINSKI', 'CONRADINHO', 'GUARAPUAVA', 'PR', 9);
INSERT INTO ENDERECO VALUES(NULL, 'RUA XV DE NOVEMBRO', 'MORRO ALTO', 'GUARAPUAVA', 'PR', 10);
INSERT INTO ENDERECO VALUES(NULL, 'VICENTE MACHADO', 'CENTRO', 'GUARAPUAVA', 'PR', 11);
INSERT INTO ENDERECO VALUES(NULL, 'SALDANHA MARINHO', 'CENTRO', 'GUARAPUAVA', 'PR', 12);

SELECT * FROM ENDERECO;



/* INSERÇÕES EM RELACIONAMETO 1XN: */
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '78458743', 8);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '78458453', 8);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '78458843', 8);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '78455643', 10);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '78438743', 10);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '78418743', 11);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '78428743', 11);

