/* Filtrando Valores Nulos */

SELECT NOME, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;


SELECT NOME, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;



/* CLAUSULA UPDATE (WHERE -> MELHOR AMIGO DA VIA PRA VIDA INTEIRA)*/
UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM'
WHERE NOME = 'LILIAN';


UPDATE CLIENTE
SET NOME = 'LILIAN CABRAL'
WHERE NOME = 'LILIAN';

UPDATE CLIENTE
SET EMAIL = 'MARIAJULIANE@GMAIL.COM'
WHERE NOME = 'MARIA JULIANE DE ALMEIDA';

INSERT INTO CLIENTE VALUES('ALINE SANTOS', 'F', 'SANTOSALINE@GMAIL.COM', 091234554, '984234544', 'RUA DAS ORQUIDEAS - 1090 - CURITIBA - PR');



/* CLAUSULA DELETE (WHERE -> MELHOR AMIGO DA VIA PRA VIDA INTEIRA*/

SELECT COUNT(*) FROM CLIENTE;
/*TOTAL = 7*/

SELECT COUNT(*) FROM CLIENTE
WHERE NOME = 'DIABO LOIRO';

DELETE FROM CLIENTE
WHERE NOME = 'ALINE SANTOS';


SELECT 6 - 1;
