
/*BANCO DE DADOS = LIVRARIA
 TABELA = LIVROS */
 
 /*ATRIBUTOS*/
 NOME_DO_LIVRO - CARACTER(75)
 NOME_DO_AUTOR - CARACTER(30)
SEXO_DO_AUTOR - CARACTER(1)
NUMERO_DE_PAGINAS - CARACTER(4)
NOME_DA_EDITORA - CARACTER(30)
VALOR_DO_LIVRO - NUMERICO(6)
ESTADO_UF_DA_EDITORA - CARACTER(2)
ANO_PUBLICACAO - CARACTER(4)

/*CRIACAO DO BANCO*/
CREATE DATABASE LIVRARIA;

USE LIVRARIA;


/*CRIACAO DA TABELA*/
CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(75),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR(1),
	NUMERO_DE_PAGINAS CHAR(4),
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO FLOAT(6),
	ESTADO_UF_DA_EDITORA CHAR(2),
	ANO_PUBLICACAO CHAR(4)
	
);


/*INSERINDO DADOS NO BANCO*/
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Cavaleiro Real', 'Ana Claudia', 'F', '465', 'Atlas', 49.9, 'RJ', '2009');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('SQL Para Leigos', 'Joao Nunes', 'M', '450', 'Addison', 98.0, 'SP', '2018');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Receitas Caseiras', 'Celia Tavares', 'F', '210', 'Atlas', 45.0, 'RJ', '2008');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Pessoas Efetivas', 'Eduardo Santos', 'M', '390', 'Beta', 78.99, 'RJ', '2018');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Habitos Saudaveis', 'Eduardo Santos', 'M', '630', 'Beta', 150.98, 'RJ', '2019');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('A Casa Marrom', 'Hermes Macedo', 'M', '250', 'Bubba', 60.0, 'MG', '2016');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Estacio Querido', 'Geraldo Francisco', 'M', '310', 'Insignia', 100.0, 'ES', '2015');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Pra Sempre Amigas', 'Leda Silva', 'F', '510', 'Insignia', 78.98, 'ES', '2011');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('Copas Inesqueciveis', 'Marco ALcantara', 'M', '200', 'Larson', 130.98, 'RS', '2008');
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICACAO) VALUES
('O Poder da Mente', 'Clara Mafra', 'F', '120', 'Continental', 56.58, 'RS', '2017');


/*BUSCAR TODOS OS DADOS*/
SELECT * FROM LIVROS;


/*MOSTRAR NOME DO LIVRO E DA EDITORA*/
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;


/*Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino*/
SELECT NOME_DO_LIVRO, ESTADO_UF_DA_EDITORA FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M';


/*Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino*/
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS
WHERE SEXO_DO_AUTOR = 'F';


/*Trazer os valores dos livros das editoras de São Paulo*/
SELECT VALOR_DO_LIVRO FROM LIVROS
WHERE ESTADO_UF_DA_EDITORA LIKE 'SP';

/* Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).*/
SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M' AND ESTADO_UF_DA_EDITORA = 'RJ' OR ESTADO_UF_DA_EDITORA = 'SP';


 
 

