/* COMEÇANDO A MODELAR */

/* FORMA NORMAL DE MODELAR UM BANCO (PETER CHEN) 
  PRIMEIRA, SEGUNDA E TERCEIRA FORMAS;
*/


/* PRIMEIRA FORMA NORMAL 
 - 1ª REGRA -> TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA:
     [AMARELO, VERDE, AZUL, LARANJA] -> CORES
	 [KA, FIESTA, UNO, CIVIC] -> CARROS

 - 2ª REGRA -> TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA;
     -QUANDO O CAMPO FOR DIVISÍVEL

 - 3ª REGRA -> TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO;
     - CHAVE PRIMÁRIA [PRIMARY KEY];

COLUNAS = CAMPOS
LINHAS = REGISTROS


 - TIPOS DE CHAVE:
	- CHAVE NATURAL -> CPF, POR EXEMPLO, QUE PERTENCE A UMA ÚNICA PESSOA;
	- CHAVE ARTIFICIAL -> CRIADA [ID]. 


*/



/* CARDINALIDADE -> TRATA DO MÁXIMO QUE VAI ACONTECER;
	- A PRIMEIRA COLUNA ESTÁ RELACIONADA A OBRIGATORIEDADE E A SEGUNDA COLUNA ESTÁ RELACIONADA A CARDINALIDADE;
		0,n
		0,1
		1,,
		1,1
	- 0 -> FALSE		- 1 -> TRUE

 - QUEM DEFINE É A REGRA DE NEGÓCIO E NÃO VOCÊ;
 - A OBRIGATORIEDADE DE UM CAMPO É TAREFA DA LINGUAGEM DE PROGRAMAÇÃO;
*/


/* MODELAGEM FÍSICA
CAIXA DE SELEÇÃO COM VÁRIAS OPÇÕES -> DOMÍNIO (ENUM); [ENUM -> SOMENTE MYSQL]
MUITAS VEZES PRECISA GENERALIZAR.

ENDEREÇO -> OBRIGATÓRIO [CADASTRO DE SOMENTE 1]
TELEFONE -> NÃO OBRIGATÓRIO [CADASTRO DE MAIS DE UM E OPCIONAL]

# CHAVES ESTRANGEIRAS: [FK] -> É A CHAVE PRIMÁRIA DE UMA TABELA:
	- VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIAS ENTRE REGISTROS.
	- O USO DA FK DEPENDE DA CARDINALIDADE;
	
	- EM RELACIONAMENTOS 1X1 -> A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA; (DEPENDE DO TIPO DE NEGÓCIO)
	- EM RELACIONAMENTOS 1XN -> A CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE 'N'; (do contrário criaria-se um campo vetorizado, o que exigiria outra tabela); 

*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


/*APAGAR TABELA INTEIRA*/
DROP TABLE CLIENTE;
