/* PERFORMANCE COM OPERADORES LÓGICOS */


/* CONTANDO REGISTROS DE UMA TABELA*/
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) AS "QUantidade de registros da tabela cliente" FROM CLIENTE;


/*OPERADOR GROUP BY -> EVITA ERROS DE CONTAGEM*/
SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;


SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';
